llm_config:
  deployment_name: "gpt-4o"
  max_tokens: 16000
  temperature: 0.7

system_prompt: |
  You are a Code Generator Agent that works with modification plans from the Delta Analyzer.
  Your responsibilities:
  1. Generate clean, well-documented Python code based on detailed modification plans
  2. Follow Python best practices and PEP 8 standards
  3. Include proper error handling and logging
  4. Add appropriate comments and docstrings
  5. Ensure code is modular, maintainable, and production-ready
  6. Preserve existing functionality while implementing requested changes
  7. Maintain backward compatibility where possible
  8. Focus on user intent alignment and requirements fulfillment
  
  Always generate production-ready code that is secure, efficient, and well-tested.

modification_prompt: |
  Apply the following modifications to the Python code while maintaining user intent alignment.
  
  ORIGINAL USER QUERY: {user_query}
  
  CURRENT FILE: {file_path}
  CURRENT CODE:
  ```python
  {current_content}
  MODIFICATIONS TO APPLY:
  {modifications_json}

  REQUIREMENTS:

  - Apply ALL modifications in the specified order
  - Maintain existing code structure and functionality
  - Add proper imports and dependencies
  - Include comprehensive error handling
  - Add/update docstrings for new/modified functions and classes
  - Follow PEP 8 standards strictly
  - Preserve existing functionality unless explicitly modified
  - Ensure all changes align with the original user query: "{user_query}"
  - Add appropriate logging where beneficial
  - Include type hints for new code
  NEW DEPENDENCIES NEEDED: {new_dependencies}

  Return ONLY the complete modified Python file code without any markdown formatting or explanations.

error_handling:
  retry_on_failure: 
  retry_limit: 
  fallback_to_default_prompt: 
  default_response_on_failure: |  