---
  config_generation_prompt: |
    You are a config generator agent. Analyze the provided configuration chunk based on the user query.
    You should also take into account the previously updated config from earlier analysis as feedback if available.
    Extract **only** the relevant information necessary to fulfill the user's query and adhere to the following schema:
    {{{{ "<key>" : "<value>", ....}}}}
    ## Inputs:
    ### User Query:
    {user_query}
    ### Previously Updated Config (Feedback):
    {feedback_config}
    ### Configuration Chunk:
    {config_chunk}
    ## Task:
    - Use the inputs, including feedback and summary if available from previous updated config, to analyze necessary dependencies and configurations.
    - Generated an output JSON with the schema:
      {{{{ "<key>" : "<value>", ....}}}}
    - Only include the relavant configuration required to fulfil the query.
    - The generated new config must have the same schema and casing which is followed in Configuration Chunk version so it can be easily integrated.
    - Do not new keys strictly in the updated config, so if you are creating a operation use same keys as Configuration Chunk.
    - please provide a summary of each object change ypu have done for a chunk so it will be used as feedback for next loop.


    output will be have two components :
    1. Generated and output JSON with the schema
    2. The summary of the config change

    output :- {{{{ "<key>" : "<value>", ....}}}} | summary

    - the output must be simple json based on Configuration Chunk only take information the feedback.
    - dont add keys in output as edits1 or edit2 just simple json.

    --- Generated only the JSON output below ----


  extract_table_names_prompt: |
    You are a database expert.
    - Please analyze the following user query and extract all table names mentioned in the query.
    - Make sure that you return all the table names in the query separated by ",".
    - Only use the table names which are used in the query, do not make something up.
    - Always choose the table which has to be updated.
    - if there are multiple tables return only the tables where modification has to be made.
    - Do not include the source/reference tables.
    - Do not include any extra information in the output.
    - In some cases the table name will also be included with .json. So include that as table name
    Examples:
      1. update the data transformation logic in sample_config.json -> sample_config.json
      2. update the data transformation logic in sample_config -> sample_config
    Query: {user_query}